apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: admin.mooney.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mooney-django-service
                port:
                  number: 8000
