# Generated by Django 3.2.5 on 2024-02-08 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ProductCategory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='product_category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table='product_category',
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='product_image',
        ),
    ]
