# Generated by Django 3.2.5 on 2024-03-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('CSH', 'Cash'), ('CHK', 'Check'), ('CRC', 'Credit Card'), ('DBT', 'Debit Card'), ('BKT', 'Bank Transfer'), ('BLT', 'Boleto'), ('PIX', 'PIX'), ('EWT', 'E-Wallet')], default='CSH', max_length=3, verbose_name='Payment Type')),
                ('description', models.CharField(blank=True, help_text='Optional description of the payment method.', max_length=255, verbose_name='Description')),
                ('payment_date', models.DateTimeField(auto_now_add=True, help_text='Date and time the payment was registered.', verbose_name='Payment Date')),
                ('issuing_bank', models.CharField(blank=True, help_text='Issuing bank for checks or bank transfers.', max_length=50, verbose_name='Issuing Bank')),
                ('number', models.CharField(blank=True, help_text='Check or card number.', max_length=20, verbose_name='Number')),
                ('validity', models.DateField(blank=True, help_text='Card validity date, if applicable.', null=True, verbose_name='Validity')),
                ('payer_cpf_cnpj', models.CharField(blank=True, help_text='Payer’s CPF or CNPJ for PIX or boletos.', max_length=14, verbose_name='Payer CPF/CNPJ')),
                ('pix_key', models.CharField(blank=True, help_text='PIX key for payments via PIX.', max_length=255, verbose_name='PIX Key')),
                ('e_wallet_provider', models.CharField(blank=True, help_text='Provider of the E-Wallet, if applicable.', max_length=50, verbose_name='E-Wallet Provider')),
            ],
        ),
    ]
