# Generated by Django 3.2.5 on 2024-03-16 03:48

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Modificado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('payment_type', models.CharField(choices=[('CSH', 'Cash'), ('CHK', 'Check'), ('CRC', 'Credit Card'), ('DBT', 'Debit Card'), ('BKT', 'Bank Transfer'), ('BLT', 'Boleto'), ('PIX', 'PIX'), ('EWT', 'E-Wallet')], default='CSH', max_length=3, verbose_name='Payment Type')),
                ('description', models.CharField(blank=True, help_text='Optional description of the payment method.', max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'db_table': 'payment_method',
            },
        ),
    ]
