# Generated by Django 3.2.5 on 2024-03-07 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_auto_20240307_1750'),
        ('customer', '0002_auto_20240307_1750'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salepayment',
            name='method',
        ),
        migrations.RemoveField(
            model_name='salepayment',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='salepaymentinstallment',
            name='sale_payment',
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'Sale Item', 'verbose_name_plural': 'Sale Items'},
        ),
        migrations.AddField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Seller'),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('creation', 'Order Creation'), ('billing', 'Billing'), ('payment_pending', 'Payment Pending'), ('payment_processing', 'Payment Processing'), ('payment_approved', 'Payment Approved'), ('payment_denied', 'Payment Denied'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('refunded', 'Refunded')], default='creation', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sale Date and Time'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sale.sale', verbose_name='Sale'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sale Price'),
        ),
        migrations.AlterModelTable(
            name='sale',
            table='sale',
        ),
        migrations.AlterModelTable(
            name='saleitem',
            table='sale_item',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='SalePayment',
        ),
        migrations.DeleteModel(
            name='SalePaymentInstallment',
        ),
    ]
