# Generated by Django 3.2.5 on 2024-02-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(choices=[('UTC', 'Coordinated Universal Time'), ('EST', 'Eastern Standard Time'), ('CST', 'Central Standard Time'), ('MST', 'Mountain Standard Time'), ('PST', 'Pacific Standard Time')], default='UTC', max_length=50, verbose_name='Preferred Timezone'),
        ),
    ]
