# Generated by Django 3.2.5 on 2024-02-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese (Brazil)')], default='en', max_length=10, verbose_name='Preferred Language'),
        ),
    ]
