apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: static-volume
              mountPath: /app/mooney/static
            #- name: nginx-config-volume
            #mountPath: /etc/nginx/nginx.conf
      volumes:
        - name: static-volume
          hostPath:
            path: /tmp
          #persistentVolumeClaim:
          #  claimName: static-pvc
        #- name: nginx-config-volume
        #  configMap:
        #    name: nginx-config
