# Generated by Django 3.2.5 on 2024-03-07 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_auto_20240307_1750'),
        ('sale', '0002_auto_20240307_1750'),
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Modificado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10, verbose_name='Transaction Status')),
                ('type_transaction', models.CharField(choices=[('sale', 'Sale')], max_length=4, verbose_name='Transaction Type')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('total_discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Discount Amount')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net Amount')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transaction',
            },
        ),
        migrations.CreateModel(
            name='SaleTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transaction.transaction')),
                ('sale_transaction_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10, verbose_name='Sale Transaction Status')),
                ('sale_transaction_type', models.CharField(choices=[('expense', 'Expense'), ('revenue', 'Revenue')], max_length=10, verbose_name='Sale Transaction Type')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tax Amount')),
                ('sale_date', models.DateTimeField(verbose_name='Sale Date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Customer')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.paymentmethod', verbose_name='Payment Type')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.sale', verbose_name='Sale')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Seller')),
            ],
            options={
                'verbose_name': 'Sale Transaction',
                'verbose_name_plural': 'Sales Transactions',
                'db_table': 'transaction_sale',
            },
            bases=('transaction.transaction',),
        ),
        migrations.CreateModel(
            name='PaymentInstallmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], max_length=10, verbose_name='Status')),
                ('installment', models.IntegerField(verbose_name='Installment Number')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('total_discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Discount Amount')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net Amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tax Amount')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.paymentmethod', verbose_name='Payment Method')),
                ('sale_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.saletransaction', verbose_name='Sale Transaction')),
            ],
            options={
                'verbose_name': 'Payment of Transaction Installments',
                'verbose_name_plural': 'Payments of Transaction Installments',
                'db_table': 'transaction_payment_installment',
            },
        ),
    ]
