# Generated by Django 3.2.5 on 2024-03-11 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinstallmentsaletransaction',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Net Amount'),
        ),
        migrations.AlterField(
            model_name='paymentinstallmentsaletransaction',
            name='sale_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_installments', to='transaction.saletransaction', verbose_name='Sale Transaction'),
        ),
        migrations.AlterField(
            model_name='paymentinstallmentsaletransaction',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Tax Amount'),
        ),
        migrations.AlterField(
            model_name='paymentinstallmentsaletransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='paymentinstallmentsaletransaction',
            name='total_discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total Discount Amount'),
        ),
        migrations.AlterField(
            model_name='paymentmethodsaletransaction',
            name='sale_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='transaction.saletransaction', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Net Amount'),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='sale_transaction_type',
            field=models.CharField(choices=[('expense', 'Expense'), ('revenue', 'Revenue')], default='expense', max_length=10, verbose_name='Sale Transaction Type'),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Tax Amount'),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='total_discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total Discount Amount'),
        ),
        migrations.AlterField(
            model_name='saletransactionitem',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Sale Price'),
        ),
    ]
