# Generated by Django 3.2.5 on 2024-03-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_saletransaction_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinstallmentsaletransaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10, verbose_name='Status'),
        ),
    ]
