# Generated by Django 3.2.5 on 2024-03-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_auto_20240312_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='saletransaction',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Total Quantity'),
        ),
    ]
